Repository guardian/commercial, pull requests merged in 2021-12, with the labels that each got.

#434 feat: Add time to CMP UI to commercial metrics
  src/EventTimer.ts
Labels: enhancement

#439 docs: Restructure docs folder
  docs/ad-render-flow.md
  docs/ad-render-flow/ad-render-flow-01.excalidraw
  docs/ad-render-flow/ad-render-flow-01.png
  docs/ad-render-flow/readme.md
  docs/google-ad-manager-advertising/readme.md
  docs/header-bidding/header-bidding-gam-line-item-match.png
  docs/header-bidding/header-bidding-gam-line-items.png
  docs/header-bidding/header-bidding-process.excalidraw
  docs/header-bidding/header-bidding-process.png
  docs/header-bidding/readme.md
Labels: documentation

#438 docs: Spacefinder documentation
  docs/spacefinder/readme.md
  docs/spacefinder/spacefinder-article-body-example.png
  docs/spacefinder/spacefinder-equation.png
  docs/spacefinder/spacefinder-process-visualised.excalidraw
  docs/spacefinder/spacefinder-process-visualised.png
Labels: documentation

#446 feat: Pick defined values from object
  .eslintrc.json
  package.json
  src/detectAdBlocker.ts
  src/targeting/pick-targeting-values.spec.ts
  src/targeting/pick-targeting-values.ts
  src/targeting/session.ts
  yarn.lock
Labels: enhancement, targeting 🎯

#445 feat: Ad Targeting – Shared
  src/targeting/content.spec.ts
  src/targeting/content.ts
  src/targeting/shared.spec.ts
  src/targeting/shared.ts
Labels: targeting 🎯

#447 chore(deps): Bump dependencies 2021-12-08
  yarn.lock
Labels: dependencies

#448 fix(types): Pick targeting keys + use `type-fest`
  package.json
  src/targeting/pick-targeting-values.spec.ts
  src/targeting/pick-targeting-values.ts
  yarn.lock
Labels: dependencies

#461 chore(deps-dev): Bump dependencies 2021-12-21
  yarn.lock
Labels: dependencies

#455 feat: unify getSessionTargeting API
  src/targeting/content.ts
  src/targeting/session.spec.ts
  src/targeting/session.ts
Labels: targeting 🎯
