Repository guardian/commercial, pull requests merged in 2023-11, with the labels that each got.

#1133 Provide the full hash for prebid in dependencies
  .changeset/thin-goats-lay.md
  package.json
  yarn.lock
Labels: dependencies

#1141 add logic for feature swtich
  .changeset/proud-turkeys-drive.md
  src/commercial.consentless.ts
  src/standalone.commercial.ts
Labels: [beta] @guardian/commercial

#1138 Add Index site id for `320x50` size ads
  src/lib/header-bidding/prebid/bid-config.spec.ts
  src/lib/header-bidding/prebid/bid-config.ts
Labels: wip 🥒

#1145 Unify centring slots in container to a single class
  .changeset/olive-meals-travel.md
  src/lib/dfp/render-advert-label.ts
  src/lib/dfp/render-advert.ts
  src/lib/high-merch.ts
Labels: [beta] @guardian/commercial

#1155 Enable inserting new inline ad slots when new blocks are created on liveblogs
  .changeset/quick-ligers-fix.md
  playwright/fixtures/pages/blogs.ts
  playwright/lib/util.ts
  playwright/tests/parallel-3/liveblog-ad-limit.spec.ts
  playwright/tests/parallel-3/liveblog-inline-slots.spec.ts
  playwright/tests/parallel-3/liveblog-live-update.spec.ts
  src/spacefinder/liveblog-adverts.spec.ts
  src/spacefinder/liveblog-adverts.ts
Labels: [beta] @guardian/commercial
