Repository guardian/commercial, pull requests merged in 2024-01, with the labels that each got.

#1167 Consolidate "init" modules in their own folder
  playwright/lib/load-page.ts
  playwright/lib/util.ts
  src/commercial.consentless.ts
  src/dfp/fill-static-advert-slots.ts
  src/dfp/lazy-load.spec.ts
  src/init/consented/ad-free-slot-remove.ts
  src/init/consented/article-aside-adverts.spec.ts
  src/init/consented/article-aside-adverts.ts
  src/init/consented/article-body-adverts.spec.ts
  src/init/consented/article-body-adverts.ts
  src/init/consented/comment-adverts.spec.ts
  src/init/consented/comment-adverts.ts
  src/init/consented/comments-expanded-advert.ts
  src/init/consented/comscore.spec.ts
  src/init/consented/comscore.ts
  src/init/consented/high-merch.ts
  src/init/consented/ipsos-mori.ts
  src/init/consented/liveblog-adverts.spec.ts
  src/init/consented/liveblog-adverts.ts
  src/init/consented/mobile-sticky.ts
  src/init/consented/prepare-a9.spec.ts
  src/init/consented/prepare-a9.ts
  src/init/consented/prepare-googletag.spec.ts
  src/init/consented/prepare-googletag.ts
  src/init/consented/prepare-permutive.spec.ts
  src/init/consented/prepare-permutive.ts
  src/init/consented/prepare-prebid.spec.ts
  src/init/consented/prepare-prebid.ts
  src/init/consented/redplanet.spec.ts
  src/init/consented/redplanet.ts
  src/init/consented/remove-consented-ads-on-consent-change.spec.ts
  src/init/consented/remove-consented-ads-on-consent-change.ts
  src/init/consented/remove-slots.ts
  src/init/consented/teads-cookieless.ts
  src/init/consented/third-party-tags.spec.ts
  src/init/consented/third-party-tags.ts
  src/init/consented/track-gpc-signal.ts
  src/init/consented/track-scroll-depth.ts
  src/init/consentless/define-slot.ts
  src/init/consentless/dynamic/article-inline.ts
  src/init/consentless/dynamic/exclusion-slot.ts
  src/init/consentless/init-fixed-slots.ts
  src/init/consentless/prepare-ootag.ts
  src/init/consentless/render-advert-label.spec.ts
  src/init/consentless/render-advert-label.ts
  src/init/shared/set-adtest-cookie.ts
  src/init/shared/set-adtest-in-labels-cookie.ts
  src/standalone.commercial.ts
Labels: health

#1207 add to readme for testing on code
  README.md
  scripts/bump_commercial.sh
Labels: [beta] @guardian/commercial

#1222 Update Prebid to resolve peer dependency mismatches with DCR
  .changeset/neat-mayflies-glow.md
  package.json
  yarn.lock
Labels: [beta] @guardian/commercial

#1236 Dependencies | Update `@guardian/identity-auth` and peer dependencies
  .changeset/silent-ghosts-rush.md
  package.json
  src/core/send-commercial-metrics.ts
  yarn.lock
Labels: dependencies

#1233 Update @guardian/consent-management-platform to 13.8.0
  .changeset/six-pants-divide.md
  package.json
  yarn.lock
Labels: [beta] @guardian/commercial
